### ISSUE TITLE
Reporte de Erros

### ISSUE THREAD

**Issue by Kitsune912** [Ludeon/RimWorld-PortugueseBrazilian#137]
Se você encontrar algum erro,

Por favor o reporte neste Issue.

:)

**Comment by almir-neto** [comment]
A palavra "português" quando selecionado a língua na interface, o mesmo botão que antes aparecia "English" aparece "Portugûes". Tentei achar o arquivo para editar e mandar a pr mas não encontrei.

Print do erro dentro do jogo:
![Sem título](https://user-images.githubusercontent.com/85481415/127566837-f37f914a-52e3-4504-aa48-b4101de230ac.png)

**Comment by ElioNETO-trad** [comment]
Olá,

e obrigado por sua mensagem! De fato, este errou passou batido na última atualização, mas já foi corrigido. 

Obrigado!

Elio NETO

**Comment by Inglix** [comment]
I apologize for the English bug report, but while I'm reporting an issue with the Brazilian Portuguese translation, I can't actually read/write the language. This was brought to my attention by a Brazilian user of one of my mods, and while my mod wasn't actually involved in the issue he was having, once we identified which of the mods he was using was responsible we figured out what was happening.

In \DefInjected\ThingDef\Buildings_Ideo.xml there are translations for _label_ and _description_ for several comps on the BiosculpterPod. The comps are referred to by an index number rather than their names. This is fine the majority of the time, but the Lights Out! mod adds a new comp to BuildingBase, which then changes the indexing of the comps on the BiosculpterPod. 

So to fix this, each comp should be referenced by name rather than index. Here's an example:

Change this...
**BiosculpterPod.comps.3.label**

to this... 
**BiosculpterPod.comps.CompBiosculpterPod_MedicCycle.label**

I grabbed that example from the French translation files in case you just want to quickly snag them from there. There's also one instance of this being done for the NeuralSupercharger which should also be fixed.

**Comment by ElioNETO-trad** [comment]
> I apologize for the English bug report, but while I'm reporting an issue with the Brazilian Portuguese translation, I can't actually read/write the language. This was brought to my attention by a Brazilian user of one of my mods, and while my mod wasn't actually involved in the issue he was having, once we identified which of the mods he was using was responsible we figured out what was happening.
> 
> In \DefInjected\ThingDef\Buildings_Ideo.xml there are translations for _label_ and _description_ for several comps on the BiosculpterPod. The comps are referred to by an index number rather than their names. This is fine the majority of the time, but the LightsOut mod adds a new comp to BuildingBase, which then changes the indexing of the comps on the BiosculpterPod.
> 
> So to fix this, each comp should be referenced by name rather than index. Here's an example:
> 
> Change this...
> **BiosculpterPod.comps.3.label**
> 
> to this...
> **BiosculpterPod.comps.CompBiosculpterPod_MedicCycle.label**
> 
> I grabbed that example from the French translation files in case you just want to quickly snag them from there. There's also one instance of this being done for the NeuralSupercharger which should also be fixed.

Hi Inglix,

thank you for your message. I'm taking a look on it and I have basic knowledge on how calls work. I'm trying to figure it out how I could change the calls and where I could find such information. What I can do to fix it is to copy exactly what the French team did (I also contribute to the French translation, but it wasn't me who fixed it). I'm going to do that, and as soon as I upload it, I write it here. 

Elio NETO

**Comment by KitsuneModder** [comment]
Opa,

Estava vendo a correção, encontrei um pequeno erro de digitação.

![image](https://user-images.githubusercontent.com/81825142/132957522-4fc2f757-25a4-484d-bd76-89b2ae21f36f.png)

''.descriptionn'' (2n)

**Comment by ElioNETO-trad** [comment]
> Opa,
> 
> Estava vendo a correção, encontrei um pequeno erro de digitação.
> 
> ![image](https://user-images.githubusercontent.com/81825142/132957522-4fc2f757-25a4-484d-bd76-89b2ae21f36f.png)
> 
> ''.descriptionn'' (2n)

Olá Kitsune,

obrigado pelos olhos de águia! Corrigi.

Elio NETO

**Comment by Inglix** [comment]
There's another bug related to the Biosculpter in your translation, this time related to the most recent update to the game. Biosculpter cycles can now require more than just nutrition to run a cycle. The bioregeneration cycle now requires 2 glitterworld medicine, so the text for BiosculpterLoadingStartedMessage in Keyed\Misc_Gameplay.xml has been changed and needs to be updated in this translation.

The English version of this string changed from this:
**Once the biosculpter pod is filled with {NUTRITION} nutrition, select a colonist and right-click on the biosculpter pod or a downed person to start the cycle.**

To this:
**Once the biosculpter pod is filled with {INGREDIENTS}, select a colonist and right-click on the biosculpter pod or a downed person to start the cycle.**

**Comment by JonathanxD** [comment]
Tem um erro [nessa linha aqui](https://github.com/Ludeon/RimWorld-PortugueseBrazilian/blob/ff4cce37704b87f4027f0f611035851383c8b0d0/Core/Keyed/Dialogs_Various.xml#L553-L554), a lógica está trocada, o comentário está certo, mas na tradução diz que positivo vende e negativo compra, mas na real é o contrário, positivo compra e negativo vende, como está no comentário e pude confirmar na [wiki](https://rimworldwiki.com/wiki/Trade) também (além de verificar in-game).

**Comment by LoboMetalurgico** [comment]
Olá @JonathanxD, obrigado por reportar este problema! Vamos corrigir o quanto antes.

**Comment by LoboMetalurgico** [comment]
Este issue será fechado em favor da criação de novos a cada problema encontrado, dessa forma, será mais fácil para a equipe organizar o que já foi feito e o que não, além de termos um controle interno mais preciso.
