### ISSUE TITLE
Erro ao testar a Tradução

### ISSUE THREAD

**Issue by hugolino1** [Ludeon/RimWorld-PortugueseBrazilian#41]
Quando tento testar as traduções que eu fiz (e aquelas que baixei daqui) os nomes dos personagens ficam tipo {0}. Alguém sabe arrumar?

**Comment by RafaelReifel** [comment]
qual arquivos mexesse?

isso do {0} é o formato de chaves que eles usam
https://ludeon.com/forums/index.php?topic=43979.0

{0} resulta em 
{0}: John, a cat, a dog (short name if possible, otherwise indefinite form of the pawn kind)

ele diz que vai tentar pegar o menor nome ou forma indefinida,
se nao tiver nenhum dos dois deve bugar e aparecer so o {0}

**Comment by hugolino1** [comment]
Sei disso mas, quando a tradução é a original funciona perfeitamente. Não creio que deveria bugar.

**Comment by RafaelReifel** [comment]
as traducoes que aparecem os {0} você modificou elas?

**Comment by arxdsilva** [comment]
@hugolino1 abre um PR com as alterações que vc fez pra gente ter uma noção do que está acontecendo
